https://git-lfs.github.com for BLOB file

wget --user=jeffcui-3 --ask-password --no-check-certificate https://github.com/.../GoogleNews-...bin.gz 

or downloading from browser with raw=true
https://github.com/.../GoogleNews..bin.gz?raw=true

file <BLOB file> 
xxd <large binary file> | head

alias ssh='ssh -o TCPKeepAlive=yes -o ServerAliveInterval=50'

ssh-keygen -t rsa
ssh <user>@<hostname> mkdir -p ~/.ssh
cat ~/.ssh/id_rsa.pub | ssh <user>@<hostname> 'cat >>~/.ssh/authorized_keys'


for i in 10 11 12 13 14 15; do echo ---TESTBOX @i ---; ssh <user>@<testbox>$i 'lsof -i -n -P' 2>/dev/null | grep LISTEN; done

#find the total size of each subdirectory("data1", "data2", "data3", ....) under /home/<user>/datasets
for i in 1 2 3 4 5; do echo ---TESTBOX @i ---; ssh <user>@<testbox>$i 'du -h -max-depth=1 /home/<user>/datasets' 2>/dev/null; done

Install a new kernel in "ml-python37" environment
(ml_python37) python -m ipykernel install --user --name="KerasTF"

source activate ml_python37
(ml_python37) ipython kernel --user --name="KerasTF"

Reinstall Jupyter is the solution to this problem
https://stackoverflow.com/questions/38221181/no-module-named-tensorflow-in-jupyter
